<a href="https://colab.research.google.com/github/sulabola/Deep_Learning_with_PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Tensors

A "torch.Tensor" is a multidimentional matrix containing elements of a single data type (default: float32).

Similar to Numpy arrays. But work better with GPU's.

More suitable for deep learning.

In [1]:
import torch
import numpy as np

#### Lists

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

### Multi-dimentional list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
my_list[1]

[6, 7, 8, 9, 10]

#### NumPy Arrays

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.40859206, 0.21010061, 0.86001072, 0.17456658],
       [0.03546421, 0.92166322, 0.26656617, 0.92279096],
       [0.37458812, 0.56187943, 0.68106122, 0.9603884 ]])

In [10]:
np1.shape

(3, 4)

In [9]:
np1.dtype

dtype('float64')

#### Tensors

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3893,  3.5559,  0.9444, -1.5653],
        [-0.2014, -0.3693, -1.6924, -0.5252],
        [-0.4671,  0.1137,  1.8732,  0.0331]])

In [14]:
type(tensor_2d)

torch.Tensor

In [15]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create tensor from numpy array

In [16]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4086, 0.2101, 0.8600, 0.1746],
        [0.0355, 0.9217, 0.2666, 0.9228],
        [0.3746, 0.5619, 0.6811, 0.9604]], dtype=torch.float64)

In [17]:
type(my_tensor)

torch.Tensor