<a href="https://colab.research.google.com/github/sulabola/Deep_Learning_with_PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Tensors

A "torch.Tensor" is a multidimentional matrix containing elements of a single data type (default: float32).

Similar to Numpy arrays. But work better with GPU's.

More suitable for deep learning.

In [18]:
import torch
import numpy as np

#### Lists

In [19]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [20]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

### Multi-dimentional list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [21]:
my_list[1]

[6, 7, 8, 9, 10]

#### NumPy Arrays

In [22]:
np1 = np.random.rand(3,4)
np1

array([[9.48772765e-01, 1.41004600e-01, 3.75801637e-02, 4.55849035e-01],
       [2.21506664e-02, 6.98885503e-02, 5.71384558e-01, 2.19510546e-01],
       [8.84669526e-04, 3.02393892e-01, 2.14910885e-01, 1.00571502e-01]])

In [23]:
np1.shape

(3, 4)

In [24]:
np1.dtype

dtype('float64')

#### Tensors

In [25]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.6802, -0.1844,  0.7726,  0.6363],
        [ 0.0651, -0.0730, -0.3710,  1.1848],
        [ 0.0743,  1.0231, -0.0634,  0.9411]])

In [26]:
type(tensor_2d)

torch.Tensor

In [27]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create tensor from numpy array

In [28]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[9.4877e-01, 1.4100e-01, 3.7580e-02, 4.5585e-01],
        [2.2151e-02, 6.9889e-02, 5.7138e-01, 2.1951e-01],
        [8.8467e-04, 3.0239e-01, 2.1491e-01, 1.0057e-01]], dtype=torch.float64)

In [29]:
type(my_tensor)

torch.Tensor

#### Tensor Operations

In [30]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape and View

In [31]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Reshape if we do not know dimentions exactly

In [34]:
my_torch2 = torch.arange(12)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [36]:
my_torch2 = torch.arange(12)
my_torch2 = my_torch2.reshape(-1,3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [37]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

### Note: "view" works same as "reshape"
### Differences = Link: https://www.geeksforgeeks.org/deep-learning/whats-the-difference-between-reshape-and-view-in-pytorch/

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [38]:
### With reshape and view they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
my_torch5[1] = 4141 ### Update the second element
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [42]:
my_torch6

### Note: It has updated

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

Slices

In [43]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
my_torch7[7]

### Note: It is not grabing the number. It is a tensor at index 7

tensor(7)

In [46]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [47]:
my_torch8[:,1] ### Allthe rows of column 1.

### Note: The output looks like a row vector.

tensor([1, 3, 5, 7, 9])

In [48]:
### Return a column (like a column vector)

my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

#### Tensor Math Operations

In [49]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [50]:
### Addition (element by element)

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [51]:
### Addition (longhand)

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [52]:
### Substraction

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [53]:
### Substraction (function)

torch.sub(tensor_b, tensor_a) ### "torch.substract" is an aliace

tensor([4, 4, 4, 4])

In [54]:
### Multiplication

tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [55]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [56]:
### Division

tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [57]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [59]:
### Modulus (remainder after division)

tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [60]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [61]:
### Exponent / Power

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])